---
- name: Ensuring Homebrew Is Installed
  stat:
    path: /usr/local/bin/brew
  register: homebrew_check
- name: Installing Homebrew
  shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fail:
    msg: Occured an error when trying to install homebrew, please check http://brew.sh for more info
  when:
    - not homebrew_check.stat.exists
    - install_homebrew_if_missing
- name: Installing Homebrew Cask Packages
  homebrew_cask:
    name: "{{ brew_cask_packages }}"
    state: present
  register: result
  until: result is successful
  when: homebrew_check.stat.exists
- name: Installing Homebrew Packages
  homebrew:
    name: "{{ brew_packages }}"
    state: present
  register: result
  until: result is successful
  when: homebrew_check.stat.exists
